export const menuItemsData = [
  {
    id: 1,
    name: 'Cheers burger ',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: ' https://images.pexels.com/photos/1639565/pexels-photo-1639565.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: 2,
    name: 'Egg Burger',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: 'https://images.pexels.com/photos/1251198/pexels-photo-1251198.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: 3,
    name: 'French Fried',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
  },
  {
    id: 4,
    name: 'white sauce pasta',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: 'https://images.pexels.com/photos/803963/pexels-photo-803963.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: 5,
    name: 'Burger and fried',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: 'https://images.pexels.com/photos/1556688/pexels-photo-1556688.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: 6,
    name: 'pizza',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: 'https://images.pexels.com/photos/10337723/pexels-photo-10337723.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: 7,
    name: 'Tacos Mexican',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: 'https://images.pexels.com/photos/8448331/pexels-photo-8448331.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: 8,
    name: 'Soup Miso',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: 'https://images.pexels.com/photos/7474164/pexels-photo-7474164.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: 9,
    name: 'Banh mi Vietnam',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: ' https://images.pexels.com/photos/1483769/pexels-photo-1483769.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
  },
  {
    id: 10,
    name: 'sanwich',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: ' https://images.pexels.com/photos/7023871/pexels-photo-7023871.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: 11,
    name: 'Salad ',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: ' https://images.pexels.com/photos/6107789/pexels-photo-6107789.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: 12,
    name: 'beefsteak',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: ' https://images.pexels.com/photos/8696466/pexels-photo-8696466.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: 13,
    name: 'Filet Fish',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: 'https://images.pexels.com/photos/4663250/pexels-photo-4663250.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: 14,
    name: 'Bacon and egg muffin ',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: 'https://images.pexels.com/photos/139746/pexels-photo-139746.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: 15,
    name: 'israeli salad',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: 'https://images.pexels.com/photos/6109104/pexels-photo-6109104.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: 16,
    name: 'Pizza Egg  ',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: 'https://images.pexels.com/photos/845811/pexels-photo-845811.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: 17,
    name: 'Pork and egg rice',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: 'https://images.pexels.com/photos/2689421/pexels-photo-2689421.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
];
