export const menuItemsData = [
  {
    id: 1,
    name: 'Cheers burger ',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: ' https://images.pexels.com/photos/1639565/pexels-photo-1639565.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: 2,
    name: 'Egg Burgur',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: 'https://images.pexels.com/photos/6529815/pexels-photo-6529815.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
  },
  {
    id: 3,
    name: 'French Fried',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
  },
  {
    id: 4,
    name: 'white sauce pasta',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: '/images/bowl3.png',
  },
  {
    id: 5,
    name: 'Burger and fried',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: 'https://images.pexels.com/photos/1556688/pexels-photo-1556688.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: 6,
    name: 'pizza',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: 'https://pixabay.com/photos/pizza-bakery-products-fast-food-2000595/',
  },
  {
    id: 7,
    name: 'Chocolate Muffin',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: '/images/granola cereal bowl.png',
  },
  {
    id: 8,
    name: 'pancake',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: 'https://pixabay.com/photos/pancakes-maple-syrup-raspberries-2291908/',
  },
  {
    id: 9,
    name: 'Banh mi Vietnam',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: ' https://images.pexels.com/photos/1483769/pexels-photo-1483769.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',
  },
  {
    id: 10,
    name: 'sanwich',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: ' https://images.pexels.com/photos/7023871/pexels-photo-7023871.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: 11,
    name: 'Salad ',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: ' https://images.pexels.com/photos/6107789/pexels-photo-6107789.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: 12,
    name: 'beefsteak',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: ' https://images.pexels.com/photos/8696466/pexels-photo-8696466.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: 13,
    name: 'greek salad',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: '/images/kisspng-greek-salad-fruit-salad-spinach-salad-muesli-vegetable-salad-5a96f429ce9af3.7299622115198423458463.png',
  },
  {
    id: 14,
    name: 'Bacon and egg muffin ',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: 'https://images.pexels.com/photos/139746/pexels-photo-139746.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: 15,
    name: 'israeli salad',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: 'https://images.pexels.com/photos/6109104/pexels-photo-6109104.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: 16,
    name: 'Pizza Egg  ',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: 'https://images.pexels.com/photos/845811/pexels-photo-845811.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
  {
    id: 17,
    name: 'Pork and egg rice',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 24,
    img: 'https://images.pexels.com/photos/2689421/pexels-photo-2689421.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  },
];
